Update useStudentList.ts
solve below error
Running build command for edu_quality
$ cd walsh && yarn build
$ tsc && refine build --base=/assets/edu_quality/walsh/ && yarn copy-html-entry
src/pages/SchoolCalendar.tsx(6,42): error TS2339: Property 'school_calendar_url' does not exist on type 'Student'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at run_build_command_for_apps (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:453:5)
    at execute (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:125:23) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 230,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1569, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1490, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1970, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1970, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1353, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 907, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 77, in build
    bundle(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 255, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --apps edu_quality --run-build-command' returned non-zero exit status 1.
ERROR: bench build --app edu_quality
subprocess.CalledProcessError: Command 'bench build --app edu_quality' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 7, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/commands/make.py", line 181, in get_app
    get_app(
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/app.py", line 787, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/app.py", line 254, in install
    install_app(
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/app.py", line 969, in install_app
    build_assets(bench_path=bench_path, app=app, using_cached=using_cached)
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/utils/bench.py", line 405, in build_assets
    exec_cmd(command, cwd=bench_path, env=env)
  File "/home/frappe/.local/lib/python3.11/site-packages/bench/utils/__init__.py", line 193, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: bench build --app edu_quality

process "/bin/sh -c bench get-app file:///home/frappe/context/apps/edu_quality   `#stage-apps-edu_quality`" did not complete successfully: exit code: 1
------
[stage-0 28/32] RUN --mount=type=cache,sharing=locked,target=/home/frappe/.cache,uid=1000,gid=1000   --mount=type=bind,source=apps/edu_quality,target=/home/frappe/context/apps/edu_quality   bench get-app file:///home/frappe/context/apps/edu_quality   `#stage-apps-edu_quality`:
File "/home/frappe/.local/lib/python3.11/site-packages/bench/app.py", line 254, in install
install_app(
File "/home/frappe/.local/lib/python3.11/site-packages/bench/app.py", line 969, in install_app
build_assets(bench_path=bench_path, app=app, using_cached=using_cached)
File "/home/frappe/.local/lib/python3.11/site-packages/bench/utils/bench.py", line 405, in build_assets
exec_cmd(command, cwd=bench_path, env=env)
File "/home/frappe/.local/lib/python3.11/site-packages/bench/utils/__init__.py", line 193, in exec_cmd
raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: bench build --app edu_quality
55.63
------
Dockerfile:231
--------------------

--------------------
failed to solve: process "/bin/sh -c bench get-app file:///home/frappe/context/apps/edu_quality   `#stage-apps-edu_quality`" did not complete successfully: exit code: 1